### ISSUE TITLE
Renderer crashed — crossdomain.xml issue?

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/appension#223]
Following error messages following CTRL+C in renderer terminal when it's frozen:

	2016-12-26 15:30:18,243:INFO:aiohttp.access:165.120.119.253 - - [26/Dec/2016:20:30:18 +0000] "GET /status.json HTTP/1.1" 200 238
	65 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
	2016-12-26 15:30:18,273:INFO:aiohttp.access:108.205.63.107 - - [26/Dec/2016:20:30:18 +0000] "GET /crossdomain.xml HTTP/1.1" 404 
	14 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:50.0) Gecko/20100101 Firefox/50.0"
	2016-12-26 15:30:20,060:INFO:aiohttp.access:108.205.63.107 - - [26/Dec/2016:20:30:20 +0000] "GET /status.json HTTP/1.1" 200 2386
	5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:50.0) Gecko/20100101 Firefox/50.0"
	2016-12-26 15:30:31,468:INFO:aiohttp.access:108.205.63.107 - - [26/Dec/2016:20:30:31 +0000] "GET /status.json HTTP/1.1" 200 2386
	5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:50.0) Gecko/20100101 Firefox/50.0"
	2016-12-26 15:30:45,398:ERROR:aiohttp.server:Error handling request
	Traceback (most recent call last):
	  File "/home/mikekilmer/appension/env/lib/python3.7/site-packages/aiohttp/web_server.py", line 61, in handle_request
		resp = yield from self._handler(request)
	  File "/home/mikekilmer/appension/env/lib/python3.7/site-packages/aiohttp/web.py", line 249, in _handle
		resp = yield from handler(request)
	  File "/home/mikekilmer/appension/glitch/renderer.py", line 178, in moosic
		await resp.drain()
	  File "/home/mikekilmer/appension/env/lib/python3.7/site-packages/aiohttp/web_reqrep.py", line 888, in drain
		yield from self._resp_impl.transport.drain()
	  File "/usr/local/lib/python3.7/asyncio/streams.py", line 333, in drain
		yield from self._protocol._drain_helper()
	  File "/usr/local/lib/python3.7/asyncio/streams.py", line 211, in _drain_helper
		yield from waiter
	2016-12-26 15:30:48,324:INFO:aiohttp.access:165.120.119.253 - - [26/Dec/2016:20:30:48 +0000] "GET /status.json HTTP/1.1" 200 23865 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
	2016-12-26 15:30:50,045:INFO:aiohttp.access:108.205.63.107 - - [26/Dec/2016:20:30:50 +0000] "GET /status.json HTTP/1.1" 200 23865 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:50.0) Gecko/20100101 Firefox/50.0"
	2016-12-26 15:31:00,041:ERROR:aiohttp.server:Error handling request
	Traceback (most recent call last):
	  File "/home/mikekilmer/appension/env/lib/python3.7/site-packages/aiohttp/web_server.py", line 61, in handle_request
		resp = yield from self._handler(request)
	  File "/home/mikekilmer/appension/env/lib/python3.7/site-packages/aiohttp/web.py", line 249, in _handle
		resp = yield from handler(request)
	  File "/home/mikekilmer/appension/glitch/renderer.py", line 169, in moosic
		await asyncio.sleep(1)
	  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 476, in sleep
		return (yield from future)
	concurrent.futures._base.CancelledError
	2016-12-26 15:31:02,940:INFO:aiohttp.access:108.205.63.107 - - [26/Dec/2016:20:31:02 +0000] "GET /status.json HTTP/1.1" 200 23864 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:50.0) Gecko/20100101 Firefox/50.0"
	2016-12-26 15:31:18,264:INFO:aiohttp.ac

**Comment by MikeiLL** [comment]
https://github.com/aio-libs/aiohttp-cors might prove useful
