### ISSUE TITLE
all.mpg and status.json not syncing

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/appension#237]
It looks like the information delivered via the status.json route in renderer are not in sync with the segments of all.mp3. Even the three tracks we are listing as playing now-ish are out of range.

I _think_ that all.mp3 is behind the status.json details. Would it help to render a sync.log file that prints filename and times for adding track to all.json and info to status.json? Possibly the output of `sudo systemctl status -l glitch-renderer` will be enough. Ideally we want the first item in status.json to be the info for the most recently added track, correct?

Am still trying to wrap my head around the relationship between status.json and all.mp3. It looks like `_render_output_audio` is pretty much tracking/generating the timing, via the `rendered_until` global.

If I am understanding the code correctly, `rendered_until` is set to ten seconds prior to time.time() when the server starts, and is then incremented by the `duration_seconds` of each (pydubAudio) segment `_render_audio_output` receives, which includes:

1. bulk of track A (dub1[skip : t1_end - t2_start])
2. end of track A overlaid with track B up to it's first beat (olay1)
3. start of track B overlaid with track A following it's final beat (olay2)

So every time `_render_output_audio` gets a segment, the `rendered_until` global is incremented by the amount of seconds of the duration of that segment, as returned by pydub? And then it is never actually compared again to time.time() until the renderer is restarted again? Are we risking a drift there?

**Comment by Rosuav** [comment]
It's perpetually compared to time.time() as part of a sleep call inside `_render_output_audio`. However, the code DOES assume that there is no clock drift - that `time.time()` will increment by 1.0 every second, perfectly and without fail. This is likely to be incorrect to some degree, but it's very hard to prove how far.

We should probably be using `time.perf_counter()` instead. In fact, that's probably a drop-in replacement; there are three calls to `time.time()` and they all are just relative to each other. There's no guarantee that perf_counter is any more useful, though, and since it has an arbitrary base point, it's less useful to the client. Worth a try.

I'm going to toss in a "curiosity PR".

**Comment by MikeiLL** [comment]
After running the server for a couple of days we seem to be about 20 minutes ahead of the music with the track details.

The recent output of the renderer is:

```
Mar 05 17:52:10 indu python[23916]: 2017-03-05 17:52:10,006:INFO:glitch.database:Automatically picking track 86.
Mar 05 17:52:10 indu python[23916]: 2017-03-05 17:52:10,532:INFO:root:Sending 96741112 bytes of data for 548.4190022675737 secs of 58 Smartbunny.mp3
Mar 05 18:01:18 indu python[23916]: 2017-03-05 18:01:18,424:INFO:root:Sending 49036 bytes of data for 0.27798185941043085 secs of overlay 1
Mar 05 18:01:18 indu python[23916]: 2017-03-05 18:01:18,702:INFO:root:Sending 56092 bytes of data for 0.31798185941043083 secs of overlay 2
Mar 05 18:01:19 indu python[23916]: 2017-03-05 18:01:19,028:INFO:glitch.database:Automatically picking track 125.
Mar 05 18:01:22 indu python[23916]: 2017-03-05 18:01:22,640:INFO:root:Sending 16123488 bytes of data for 91.40299319727892 secs of 86 mike_ill_1427380634598.mp3
Mar 05 18:02:50 indu python[23916]: 2017-03-05 18:02:50,424:INFO:root:Sending 53096 bytes of data for 0.30099773242630384 secs of overlay 1
Mar 05 18:02:50 indu python[23916]: 2017-03-05 18:02:50,725:INFO:root:Sending 71792 bytes of data for 0.406984126984127 secs of overlay 2
Mar 05 18:02:51 indu python[23916]: 2017-03-05 18:02:51,132:INFO:glitch.database:Automatically picking track 94.
Mar 05 18:02:51 indu python[23916]: 2017-03-05 18:02:51,590:INFO:root:Sending 134603960 bytes of data for 763.0609977324264 secs of 125 Bulter, Chris_id61.mp3
```

I’m unclear as to how to read the data above. Does it tell us when INFO is being sent to status.json? What we want to see, I imagine is that at a certain time such-and-such a track comes out of the queue and at the same time it's track_detail object is added to `status.json`, right?

**Comment by Rosuav** [comment]
(Side point: "Bulter, Chris"?)

Can you run the server with debug logging active, please? I want to see the "sleeping for X seconds" lines, to see if there's drift happening. Add `-l debug` to the command line, possibly in `/etc/systemd/system/glitch-renderer.service`.

Twenty minutes in "a couple" of days... that's maybe half a percent. Quite a long way to be wrong. I wonder, is it possible that ffmpeg is unable to keep up? Does the audio ever fall silent while you're listening to it, and have to buffer a bit?

**Comment by MikeiLL** [comment]
Not sure why the MP3 got that name, if that's what the side note refers to. Now output of stdout looks like this in the systemd status:

```
Mar 05 20:48:46 indu python[9371]: 2017-03-05 20:48:46,106:DEBUG:glitch.database:Rendering Track(59, '59 theswales.mp3', 'The Swales', 'The Major Glitch', 153.781958333333, 1, 'Live @ Saturday Afternoon Song Swap', '', 1, 0, 5)
Mar 05 20:48:46 indu python[9371]: 2017-03-05 20:48:46,106:INFO:glitch.database:Automatically picking track 59.
Mar 05 20:48:46 indu python[9371]: 2017-03-05 20:48:46,106:DEBUG:glitch.database:Added track 59 to recent track list (now has 2/50)
Mar 05 20:48:46 indu python[9371]: 2017-03-05 20:48:46,133:DEBUG:pydub.converter:subprocess.call(['ffmpeg', '-y', '-f', 'mp3', '-i', '/tmp/tmp6gwgc0mm', '-vn', '-f', 'wav', '/tmp/tmpwj9x5303'])
Mar 05 20:48:46 indu python[9371]: 2017-03-05 20:48:46,842:INFO:root:Sending 32895600 bytes of data for 186.48299319727892 secs of 12 C. Chopek and New Retro Strings_verB.mp3
Mar 05 20:48:49 indu python[9371]: 2017-03-05 20:48:49,052:DEBUG:root:/status.json requested
Mar 05 20:48:49 indu python[9371]: 2017-03-05 20:48:49,054:INFO:aiohttp.access:108.205.63.107 - - [06/Mar/2017:01:48:49 +0000] "GET /status.json HTTP/1.1" 200 1944 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:51.0) Gecko/20100101 Firefox/51.0"
Mar 05 20:48:49 indu python[9371]: 2017-03-05 20:48:49,545:DEBUG:root:Adding another song section [1, 1048704 bytes]
Mar 05 20:48:52 indu python[9371]: 2017-03-05 20:48:52,217:DEBUG:root:Adding another song section [2, 1048660 bytes]
Mar 05 20:48:54 indu python[9371]: 2017-03-05 20:48:54,346:DEBUG:root:And sleeping for 167s until 4371191.825457673 [ofs 1484393909.888588=>1484393909.8885891 = +0.000001]
```
Have not noticed dropouts, but it does seems to take some time — like 10 seconds — for music to begin after pressing the play button in the browser. This is also pretty undesirable. Could it potentially be tied in with the slippage?

**Comment by Rosuav** [comment]
Ten seconds on first startup (ie a one-off), or does the same delay keep happening? If it's just once, it's probably the loading/setup work, and not a problem. If it keeps happening, that might be a problem.

**Comment by MikeiLL** [comment]
Consistently pretty slow to start playing. How is it for you? http://infiniteglitch.net/

**Comment by Rosuav** [comment]
I let the page completely load, which took three parts of forever, but then starting playback was nearly instant. Maybe that's a difference?

**Comment by MikeiLL** [comment]
But that wouldn't have anything to do with the audio/info slippage, would it?

**Comment by Rosuav** [comment]
It shouldn't, no. However, if playback ever pauses while you're listening to it, that could definitely affect it. Also of note would be if the server appears to be loaded, eg if `top` shows consistently high load averages and/or CPU usage percentages.

**Comment by MikeiLL** [comment]
Doesn't look like it:
```
top - 08:03:03 up 51 days,  1:24,  1 user,  load average: 0.00, 0.04, 0.00
Tasks: 133 total,   1 running, 132 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   2045224 total,  1724728 used,   320496 free,    35788 buffers
KiB Swap:   524284 total,      116 used,   524168 free.  1062756 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                         
12931 mikekil+  20   0   23640   2956   2472 R  0.3  0.1   0:00.04 top        
```

**Comment by Rosuav** [comment]
Just to be clear, that was top running on the server, right?

**Comment by MikeiLL** [comment]
Yes. Which I think speaks highly of the programming of the app, compared to the last version, right?

**Comment by MikeiLL** [comment]
So after a couple of hours running we have:

Currently playing chunk is the third one listed (Lane Steinberg), music changed and within a minute, I believe, the new chunk (SmartBunny) bumped up to the third one listed.

Then suddenly the player stopped. Had to reload page to restart.

```
● glitch-renderer.service - Infinite Glitch Renderer
   Loaded: loaded (/etc/systemd/system/glitch-renderer.service; static)
   Active: active (running) since Mon 2017-03-13 10:53:37 EDT; 3h 27min ago
 Main PID: 4342 (python)
   CGroup: /system.slice/glitch-renderer.service
           ├─4342 /home/mikekilmer/appension/env/bin/python -m glitch renderer -l debug
           └─4355 ffmpeg -ac 2 -f s16le -i - -f mp3 -
```
Output of monitor.py:
```
Unplayed: 382.83153329603374
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 380.8208558578044
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 378.8092873701826
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 376.79542461782694
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 374.78170008491725
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 372.76854246109724
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 370.7574476664886
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 368.74536128807813
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 366.7332780100405
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 364.71936460770667
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 362.70597027242184
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 360.69241185486317
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 358.6796133527532
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 356.6655480666086
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 354.6420028246939
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175

Unplayed: 352.6305901147425
49 1164.521950113587  Pamela Beth  Grossman 85.0247083333333
115 1082.1879365080968  Keith Allison 144.6661
138 937.5749659864232 CB - Radio Station ID Break 113.39755
36 824.4359863940626  Lane Steinberg 279.105416666667
58 548.4529931973666 SmartBunny 558.170625
Lag: 9.717631802894175
```

Top output
```
%Cpu(s):  0.7 us,  0.0 sy,  0.0 ni, 99.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   2045224 total,  1448784 used,   596440 free,    26644 buffers
KiB Swap:   524284 total,      116 used,   524168 free.   899764 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                              
  529 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xprtiod                                                                                                                                              
  816 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfsalloc                                                                                                                                             
  817 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 xfs_mru_cache                                                                                                                                        
  297 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 writeback                                                                                                                                            
  676 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 vmstat                                                                                                                                               
 6273 mikekil+  20   0   23652   3012   2476 R  0.0  0.1   0:00.14 top                                                                                                                                                  
 2945 root      20   0   39100   2832   2108 S  0.0  0.1   0:00.05 systemd-udevd                                                                                                                                        
 3360 root      20   0   19856   2372   2100 S  0.0  0.1   0:16.77 systemd-logind                                                                                                                                       
 2197 root      20   0   49720  16624  14196 S  0.0  0.8  13:42.75 systemd-journal                                                                                                                                      
    1 root      20   0   29884   5312   2784 S  0.0  0.3   1:57.24 systemd                                                                                                                                              
 2971 root      20   0   82684   5860   4984 S  0.0  0.3   0:00.00 sshd                                                                                                                                                 
 2975 mikekil+  20   0   82684   3936   3064 S  0.0  0.2   0:00.48 sshd                                                                                                                                                 
 3175 root      20   0   82684   6052   5184 S  0.0  0.3   0:00.01 sshd                                                                                                                                                 
 3177 mikekil+  20   0   82684   4100   3232 S  0.0  0.2   0:00.02 sshd                                                                                                                                                 
 3358 root      20   0   55184   5264   4592 S  0.0  0.3   1:40.01 sshd                                                                                                                                                 
 6289 root      20   0   81604   5964   4992 S  0.7  0.3   0:00.02 sshd                                                                                                                                                 
 6290 sshd      20   0   56528   3308   2636 S  0.0  0.2   0:00.00 sshd                                                                                                                                                 
 1873 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 scsi_tmf_2                                                                                                                                           
 1858 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 scsi_tmf_1                                                                                                                                           
 1582 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 scsi_tmf_0                                                                                                                                           
 1870 root      20   0       0      0      0 S  0.0  0.0   0:00.00 scsi_eh_2                                                                                                                                            
 1851 root      20   0       0      0      0 S  0.0  0.0   0:00.00 scsi_eh_1                                                                                                                                            
 1581 root      20   0       0      0      0 S  0.0  0.0   0:00.00 scsi_eh_0                                                                                                                                            
 3366 root      20   0  258672   3692   2088 S  0.0  0.2   3:05.47 rsyslogd                                                                                                                                             
  527 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 rpciod                                                                                                                                               
    7 root      20   0       0      0      0 S  0.0  0.0   3:01.73 rcu_sched                                                                                                                                            
    8 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcu_bh                                                                                                                                               
 1579 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 rbd                                                                                                                                                  
 1903 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 raid5wq                                                                                                                                              
 4342 mikekil+  20   0  470724 331812  10940 S  0.0 16.2   2:02.22 python      
```

**Comment by Rosuav** [comment]
Cool. So after a couple of hours of rendering, we have it well within parameters. A useful data point. Now, w need the "couple of days" data point: if that's problematic, either something's accumulating error, or it's falling behind when it reaches some specific track, or something. (Imagine a data-dependent fault eg "when the track is less than ten seconds long, time advances by ten full seconds" or something.)

**Comment by MikeiLL** [comment]
Cool. Will continue checking over the next 40 hours or so and report back.

**Comment by MikeiLL** [comment]
Day two, current track is displayed as 2 of 3 in the Info (Playing nowish) field, where yesterday was third.
Mrs. Irene Elizabeth Butler at 9:52. Then Harvey Gold comes on and is the third in the display.

**Comment by MikeiLL** [comment]
Evening of day two, currently playing song (Know it All Boyfriends) is listed second with playing now(ish).

**Comment by Rosuav** [comment]
So far, so good...

**Comment by MikeiLL** [comment]
10:30PM day two, Ralph Carney Horns playing and listed 2nd of three Playing Nowish.

**Comment by MikeiLL** [comment]
Trying to run on the server directly from command line. 

When I change `configs.http_port` to `80` getting error:

```
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 113, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/home/mikekilmer/appension/glitch/__main__.py", line 11
    def renderer(*, gain:"g"=0.0):
```

**Comment by Rosuav** [comment]
You're in 2.7 for some reason. Get yourself back onto 3.x.

**Comment by MikeiLL** [comment]
```
 sudo python3 -m glitch main renderer
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mikekilmer/appension/glitch/__main__.py", line 1, in <module>
    from . import utils
  File "/home/mikekilmer/appension/glitch/utils.py", line 8, in <module>
    import clize
ImportError: No module named 'clize'
```

```
$ which python3
/home/mikekilmer/appension/env/bin/python3
```

```
sudo /home/mikekilmer/appension/env/bin/python3 -m glitch main renderer
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mikekilmer/appension/glitch/__main__.py", line 5, in <module>
    from . import database # Let the database functions register themselves
  File "/home/mikekilmer/appension/glitch/database.py", line 18, in <module>
    _conn = psycopg2.connect(apikeys.db_connect_string)
  File "/home/mikekilmer/appension/env/lib/python3.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  role "root" does not exist
```

**Comment by MikeiLL** [comment]
Narrowing in on it, I think?

https://github.com/MikeiLL/appension/issues/237 <https://github.com/MikeiLL/appension/issues/237>

**Comment by Rosuav** [comment]
The first one is because the venv was wrong, so yeah, the next one is the solution to that. The second is because a blank connection string means "use all the defaults". I think you could change that to:

    db_connect_string = "user=mikekilmer"

in apikeys. But this really isn't how the server's meant to be run; it should be run as a non-root user and given a socket via systemd.

**Comment by MikeiLL** [comment]
Then is this maybe not a good route to troubleshooting?

**Comment by Rosuav** [comment]
Yup. Let's stick with systemd. You should be able to get all your logs through that.

**Comment by MikeiLL** [comment]
Moving current thread to [new issue.](https://github.com/MikeiLL/appension/issues/244). Closing this issue for now, even though a single browser is having drift over time, new connections display correct results.

**Comment by Rosuav** [comment]
Good to know. Thanks for monitoring this.
